const EXTENSION_NAME = "999Dice Helper";

const RAIN_NOTIFICATION_ENABLED = true;
const RAIN_AUDIO_NOTIFICATION_ENABLED = true;
const RAIN_AUDIO_NOTIFICATION_TYPE_DEFAULT = "sine";

const CHAT_NOTIFICATION_ENABLED = true;
const CHAT_AUDIO_NOTIFICATION_ENABLED = true;
const CHAT_AUDIO_NOTIFICATION_TYPE_DEFAULT = "sine";
