const EXTENSION_NAME = "999Dice Helper";

const RAIN_NOTIFICATION_ENABLED = true;
const RAIN_NOTIFICATION_TYPE = "simple";
const RAIN_AUDIO_NOTIFICATION_TYPE = "sine";

const CHAT_NOTIFICATION_ENABLED = true;
const CHAT_NOTIFICATION_TYPE = "simple";
const CHAT_AUDIO_NOTIFICATION_TYPE = "sine";
